language: c
dist: xenial
sudo: required

matrix:
  include:
    - name: Linux (gcc-8)
      os: linux
      compiler: gcc-8
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-8']
      before_install: &bs_linux
        - sudo apt-get install faketime libscope-guard-perl libtest-tcp-perl
    - name: Linux (clang)
      os: linux
      compiler: clang
      before_install: *bs_linux
    - name: Linux (OpenSSL 1.0.2)
      os: linux
      before_install:
        - sudo apt-get install faketime libscope-guard-perl libtest-tcp-perl
        - curl https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz | tar xzf -
        - cd openssl-1.0.2u
        - ./config --prefix=/usr/local/openssl-1.0.2
        - make
        - sudo make install
        - cd ..
      env:
        - PKG_CONFIG_PATH=/usr/local/openssl-1.0.2/lib/pkgconfig
    - name: macOS (Xcode)
      os: osx
      addons: &addons_macos
        homebrew:
          packages:
            - libfaketime
            - openssl
      env:
        - CMAKE_OPTS=" -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"
      before_install: &bs_macos
        - curl -L https://cpanmin.us | sudo perl - App::cpanminus
        - sudo cpanm --notest Scope::Guard
        - sudo cpanm --notest Test::TCP

script:
  - cmake ${CMAKE_OPTS} .
  - make all
  - make check
