name: "win-compile"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: openssl version
      run: |
        openssl version -a
        dir "C:\Program Files\Common Files\SSL"

    - name: build picotlsvs
      run: |
        $env:OPENSSLDIR = "C:\Program Files\Common Files\SSL"
        $env:OPENSSL64DIR = "C:\Program Files\Common Files\SSL"
        cd picotlsvs
        msbuild picotlsvs.sln