name: "win-compile"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: setup-nmake
      uses: actions/checkout@v1
      uses: ilammy/msvc-dev-cmd@v1

    - name: setup-openssl
      run: |
        git clone https://github.com/openssl/openssl
        cd openssl
        perl Configure VC-WIN64A no-asm
        nmake
      
    - name: build picotlsvs
      run: |
        $env:OPENSSLDIR = "..\openssl"
        $env:OPENSSL64DIR = "..\openssl"
        cd picotlsvs
        msbuild picotlsvs.sln